#!/bin/bash

# Replace these three settings.
PROJDIR="/home/apt9online/www/bslcks"
PIDFILE="$PROJDIR/bslcks.pid"
SOCKET="$PROJDIR/bslcks.sock"

cd $PROJDIR
if [ -f $PIDFILE ]; then
    kill `cat -- $PIDFILE`
    rm -f -- $PIDFILE
fi

python2.7 manage.py runfcgi socket=$SOCKET pidfile=$PIDFILE maxchildren=1 maxspare=1
